-- Schema Postgres pentru aplicatia eMAG (migrare din SQLite)
-- Tipuri: NUMERIC bani, TIMESTAMPTZ date, JSONB payload-uri.

CREATE TABLE IF NOT EXISTS app_meta (
  key TEXT PRIMARY KEY,
  value TEXT
);

CREATE TABLE IF NOT EXISTS settings (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  pret_transport NUMERIC(12, 4),
  procentaj_emag NUMERIC(8, 4),
  numar_produse NUMERIC(12, 2),
  mult_prp NUMERIC(12, 4),
  mult_min NUMERIC(12, 4),
  mult_max NUMERIC(12, 4),
  alte_costuri NUMERIC(12, 4),
  procentaj_alte_costuri NUMERIC(8, 4)
);

-- Legacy / import Excel (canonical = catalog_products)
CREATE TABLE IF NOT EXISTS products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cod_produs TEXT,
  nume_produs TEXT NOT NULL,
  pret_cumparare NUMERIC(12, 4),
  UNIQUE (cod_produs)
);

CREATE INDEX IF NOT EXISTS idx_products_nume_lower
  ON products (LOWER(nume_produs));

CREATE INDEX IF NOT EXISTS idx_products_cod_lower
  ON products (LOWER(cod_produs));

-- Lookup familie: un id => un singur nume (FK id_familie pe catalog/listings)
CREATE TABLE IF NOT EXISTS product_families (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL
);

-- Sursa adevarului local: produs (preturi, stoc general). Oferta eMAG remote: cache memorie.
CREATE TABLE IF NOT EXISTS catalog_products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cod_produs TEXT UNIQUE,
  nume TEXT,
  descriere TEXT,
  brand TEXT,
  ean TEXT,
  pret_cumparare NUMERIC(12, 4),
  emag_offer_id TEXT,
  part_number TEXT,
  part_number_key TEXT,
  id_familie INTEGER,
  sale_price NUMERIC(12, 4),
  recommended_price NUMERIC(12, 4),
  min_sale_price NUMERIC(12, 4),
  max_sale_price NUMERIC(12, 4),
  general_stock NUMERIC(12, 3),
  currency TEXT,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_catalog_nume_lower
  ON catalog_products (LOWER(nume));

CREATE INDEX IF NOT EXISTS idx_catalog_cod_lower
  ON catalog_products (LOWER(cod_produs));

-- Poze locale per produs (numar variabil)
CREATE TABLE IF NOT EXISTS product_images (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NOT NULL REFERENCES catalog_products(id) ON DELETE CASCADE,
  stored_name TEXT NOT NULL UNIQUE,
  original_name TEXT,
  mime_type TEXT,
  byte_size INTEGER,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_product_images_product_sort
  ON product_images (product_id, sort_order);

-- Index doar daca coloana exista (DB vechi: migrarea 003 o adauga)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'catalog_products'
      AND column_name = 'emag_offer_id'
  ) THEN
    CREATE UNIQUE INDEX IF NOT EXISTS idx_catalog_emag_offer
      ON catalog_products (emag_offer_id)
      WHERE emag_offer_id IS NOT NULL;
  END IF;
END $$;

-- Legacy / multi-canal. eMAG: doar override-uri locale (costuri, pret_minim); offer mirrors → cache.
CREATE TABLE IF NOT EXISTS marketplace_listings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel TEXT NOT NULL,
  external_id TEXT NOT NULL,
  product_id INTEGER REFERENCES catalog_products(id) ON DELETE SET NULL,
  part_number TEXT,
  part_number_key TEXT,
  name TEXT,
  description TEXT,
  brand TEXT,
  ean TEXT,
  id_familie INTEGER,
  characteristics TEXT,
  sale_price NUMERIC(12, 4),
  recommended_price NUMERIC(12, 4),
  min_sale_price NUMERIC(12, 4),
  max_sale_price NUMERIC(12, 4),
  general_stock NUMERIC(12, 3),
  estimated_stock NUMERIC(12, 3),
  stock_json JSONB,
  handling_time_json JSONB,
  status INTEGER,
  vat_id INTEGER,
  currency TEXT,
  alte_costuri NUMERIC(12, 4),
  pret_minim_override NUMERIC(12, 4),
  procentaj_emag NUMERIC(8, 4),
  commission_value NUMERIC(12, 4),
  commission_fetched_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ,
  UNIQUE (channel, external_id)
);

CREATE INDEX IF NOT EXISTS idx_listings_product
  ON marketplace_listings (product_id);

CREATE INDEX IF NOT EXISTS idx_listings_channel_ext
  ON marketplace_listings (channel, external_id);


-- offer_id = external_id numeric (id oferta canal), nu PK intern listing
CREATE TABLE IF NOT EXISTS product_pret_emag_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  offer_id INTEGER NOT NULL,
  sale_price NUMERIC(12, 4) NOT NULL,
  currency TEXT,
  recorded_at TIMESTAMPTZ NOT NULL,
  source TEXT,
  channel TEXT NOT NULL DEFAULT 'emag'
);

CREATE INDEX IF NOT EXISTS idx_pret_emag_hist_offer
  ON product_pret_emag_history (offer_id, recorded_at);

CREATE INDEX IF NOT EXISTS idx_pret_emag_hist_channel
  ON product_pret_emag_history (channel, offer_id, recorded_at DESC);

CREATE TABLE IF NOT EXISTS order_line_history (
  line_id INTEGER PRIMARY KEY,
  order_id INTEGER NOT NULL,
  product_id INTEGER,
  part_number TEXT,
  name TEXT,
  quantity NUMERIC(12, 3),
  sale_price NUMERIC(12, 4),
  status INTEGER,
  currency TEXT,
  order_date TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_order_line_product
  ON order_line_history (product_id, order_date);

CREATE TABLE IF NOT EXISTS app_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts TIMESTAMPTZ NOT NULL,
  level TEXT NOT NULL,
  source TEXT NOT NULL,
  category TEXT NOT NULL,
  message TEXT NOT NULL,
  duration_ms INTEGER,
  status INTEGER,
  detail TEXT
);

CREATE INDEX IF NOT EXISTS idx_app_logs_ts ON app_logs (ts DESC);
CREATE INDEX IF NOT EXISTS idx_app_logs_level ON app_logs (level, ts DESC);
CREATE INDEX IF NOT EXISTS idx_app_logs_cat ON app_logs (category, ts DESC);

-- Credentiale marketplace (payload AES-GCM, cheie din CREDENTIALS_ENCRYPTION_KEY)
CREATE TABLE IF NOT EXISTS marketplace_credentials (
  channel TEXT PRIMARY KEY,
  payload_enc TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO settings (id, pret_transport, procentaj_emag, numar_produse, mult_prp, mult_min, mult_max, alte_costuri)
VALUES (1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

INSERT INTO app_meta (key, value)
VALUES ('schema_version', '0')
ON CONFLICT (key) DO NOTHING;
