-- Schema Postgres pentru aplicatia eMAG (migrare din SQLite)
-- Tipuri: NUMERIC bani, TIMESTAMPTZ date, JSONB payload-uri.

CREATE TABLE IF NOT EXISTS app_meta (
  key TEXT PRIMARY KEY,
  value TEXT
);

CREATE TABLE IF NOT EXISTS settings (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  pret_transport NUMERIC(12, 4),
  procentaj_emag NUMERIC(8, 4),
  numar_produse NUMERIC(12, 2),
  mult_prp NUMERIC(12, 4),
  mult_min NUMERIC(12, 4),
  mult_max NUMERIC(12, 4),
  alte_costuri NUMERIC(12, 4),
  procentaj_alte_costuri NUMERIC(8, 4)
);

-- Legacy / import Excel (canonical = catalog_products)
CREATE TABLE IF NOT EXISTS products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cod_produs TEXT,
  nume_produs TEXT NOT NULL,
  pret_cumparare NUMERIC(12, 4),
  UNIQUE (cod_produs)
);

CREATE INDEX IF NOT EXISTS idx_products_nume_lower
  ON products (LOWER(nume_produs));

CREATE INDEX IF NOT EXISTS idx_products_cod_lower
  ON products (LOWER(cod_produs));

-- Lookup familie: un id => un singur nume (FK id_familie pe catalog/listings)
CREATE TABLE IF NOT EXISTS product_families (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL
);

-- Sursa adevarului local: produs (preturi, stoc general). Oferta eMAG remote: cache memorie.
CREATE TABLE IF NOT EXISTS catalog_products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cod_produs TEXT UNIQUE,
  nume TEXT,
  descriere TEXT,
  brand TEXT,
  ean TEXT,
  pret_cumparare NUMERIC(12, 4),
  pret_cumparare_usd NUMERIC(12, 4),
  link_cumparare TEXT,
  emag_offer_id TEXT,
  part_number TEXT,
  part_number_key TEXT,
  id_familie INTEGER,
  sale_price NUMERIC(12, 4),
  recommended_price NUMERIC(12, 4),
  min_sale_price NUMERIC(12, 4),
  max_sale_price NUMERIC(12, 4),
  general_stock NUMERIC(12, 3),
  currency TEXT,
  transport_override NUMERIC(12, 4),
  greutate NUMERIC(12, 3),
  inaltime NUMERIC(12, 2),
  lungime NUMERIC(12, 2),
  latime NUMERIC(12, 2),
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_catalog_nume_lower
  ON catalog_products (LOWER(nume));

CREATE INDEX IF NOT EXISTS idx_catalog_cod_lower
  ON catalog_products (LOWER(cod_produs));

-- Poze locale per produs (numar variabil)
-- source_url NULL = upload manual; set = descarcata din eMAG
CREATE TABLE IF NOT EXISTS product_images (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NOT NULL REFERENCES catalog_products(id) ON DELETE CASCADE,
  stored_name TEXT NOT NULL UNIQUE,
  original_name TEXT,
  mime_type TEXT,
  byte_size INTEGER,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  source_url TEXT,
  -- setul de poze: 'en' = implicit (folosit cand platforma nu are poze proprii)
  platform TEXT NOT NULL DEFAULT 'en'
);

-- DB-uri create inainte de source_url: CREATE TABLE IF NOT EXISTS nu adauga coloana.
ALTER TABLE product_images ADD COLUMN IF NOT EXISTS source_url TEXT;
ALTER TABLE product_images ADD COLUMN IF NOT EXISTS platform TEXT NOT NULL DEFAULT 'en';
ALTER TABLE product_images DROP CONSTRAINT IF EXISTS product_images_platform_chk;
ALTER TABLE product_images
  ADD CONSTRAINT product_images_platform_chk
  CHECK (platform IN ('en', 'ro', 'bg', 'hu'));

CREATE INDEX IF NOT EXISTS idx_product_images_product_sort
  ON product_images (product_id, sort_order);

CREATE INDEX IF NOT EXISTS idx_product_images_product_platform_sort
  ON product_images (product_id, platform, sort_order);

CREATE UNIQUE INDEX IF NOT EXISTS product_images_source_platform_uidx
  ON product_images (product_id, platform, source_url)
  WHERE source_url IS NOT NULL;

-- Ce set de poze am trimis ultima data pe fiecare platforma eMAG (ro/bg/hu).
CREATE TABLE IF NOT EXISTS product_images_push_state (
  product_id INTEGER NOT NULL REFERENCES catalog_products(id) ON DELETE CASCADE,
  platform TEXT NOT NULL,
  fingerprint TEXT NOT NULL,
  pushed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (product_id, platform)
);

-- Index doar daca coloana exista (DB vechi: migrarea 003 o adauga)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'catalog_products'
      AND column_name = 'emag_offer_id'
  ) THEN
    CREATE UNIQUE INDEX IF NOT EXISTS idx_catalog_emag_offer
      ON catalog_products (emag_offer_id)
      WHERE emag_offer_id IS NOT NULL;
  END IF;
END $$;

-- Override-uri locale eMAG (costuri, comision, pret_minim). Oglinda ofertelor → cache in memorie.
CREATE TABLE IF NOT EXISTS marketplace_listings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel TEXT NOT NULL,
  external_id TEXT NOT NULL,
  product_id INTEGER REFERENCES catalog_products(id) ON DELETE SET NULL,
  characteristics TEXT,
  estimated_stock NUMERIC(12, 3),
  stock_json JSONB,
  handling_time_json JSONB,
  status INTEGER,
  vat_id INTEGER,
  pret_minim_override NUMERIC(12, 4),
  procentaj_emag NUMERIC(8, 4),
  commission_value NUMERIC(12, 4),
  commission_fetched_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ,
  UNIQUE (channel, external_id)
);

CREATE INDEX IF NOT EXISTS idx_listings_product
  ON marketplace_listings (product_id);

CREATE INDEX IF NOT EXISTS idx_listings_channel_ext
  ON marketplace_listings (channel, external_id);


-- offer_id = external_id numeric (id oferta canal), nu PK intern listing
CREATE TABLE IF NOT EXISTS product_pret_emag_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- ID-urile ofertelor eMAG pot avea 13 cifre; INTEGER (max. 2.147.483.647) nu ajunge.
  offer_id BIGINT NOT NULL,
  sale_price NUMERIC(12, 4) NOT NULL,
  currency TEXT,
  recorded_at TIMESTAMPTZ NOT NULL,
  source TEXT,
  channel TEXT NOT NULL DEFAULT 'emag'
);

CREATE INDEX IF NOT EXISTS idx_pret_emag_hist_offer
  ON product_pret_emag_history (offer_id, recorded_at);

CREATE INDEX IF NOT EXISTS idx_pret_emag_hist_channel
  ON product_pret_emag_history (channel, offer_id, recorded_at DESC);

CREATE TABLE IF NOT EXISTS order_line_history (
  line_id INTEGER PRIMARY KEY,
  order_id INTEGER NOT NULL,
  channel TEXT NOT NULL DEFAULT 'emag',
  product_id INTEGER,
  part_number TEXT,
  name TEXT,
  quantity NUMERIC(12, 3),
  sale_price NUMERIC(12, 4),
  status INTEGER,
  currency TEXT,
  order_date TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_order_line_product
  ON order_line_history (product_id, order_date);

CREATE TABLE IF NOT EXISTS app_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts TIMESTAMPTZ NOT NULL,
  level TEXT NOT NULL,
  source TEXT NOT NULL,
  category TEXT NOT NULL,
  message TEXT NOT NULL,
  duration_ms INTEGER,
  status INTEGER,
  detail TEXT
);

CREATE INDEX IF NOT EXISTS idx_app_logs_ts ON app_logs (ts DESC);
CREATE INDEX IF NOT EXISTS idx_app_logs_level ON app_logs (level, ts DESC);
CREATE INDEX IF NOT EXISTS idx_app_logs_cat ON app_logs (category, ts DESC);

-- Credentiale marketplace (payload AES-GCM, cheie din CREDENTIALS_ENCRYPTION_KEY)
CREATE TABLE IF NOT EXISTS marketplace_credentials (
  channel TEXT PRIMARY KEY,
  payload_enc TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Miscari automate de stoc (comenzi eMAG, anulari, editari manuale pe eMAG, conflicte).
CREATE TABLE IF NOT EXISTS stock_movements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER REFERENCES catalog_products (id) ON DELETE SET NULL,
  channel TEXT NOT NULL DEFAULT 'emag',
  order_id TEXT NOT NULL DEFAULT '',
  line_id TEXT NOT NULL DEFAULT '',
  offer_id TEXT,
  kind TEXT NOT NULL,
  delta NUMERIC(12, 3) NOT NULL DEFAULT 0,
  stock_before NUMERIC(12, 3),
  stock_after NUMERIC(12, 3),
  emag_stock NUMERIC(12, 3),
  trendyol_status TEXT,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Idempotenta pentru comenzi: aceeasi linie nu se scade/restituie de doua ori.
CREATE UNIQUE INDEX IF NOT EXISTS uq_stock_movements_order_line
  ON stock_movements (channel, order_id, line_id, kind)
  WHERE kind IN ('order', 'order-cancel');

CREATE INDEX IF NOT EXISTS idx_stock_movements_created
  ON stock_movements (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_stock_movements_product
  ON stock_movements (product_id, created_at DESC);

-- Stocul asteptat pe eMAG per oferta (ajustat la comenzi si la push-uri proprii).
CREATE TABLE IF NOT EXISTS emag_stock_snapshot (
  offer_id TEXT PRIMARY KEY,
  general_stock NUMERIC(12, 3),
  seen_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Antet comenzi eMAG, salvat la fiecare webhook / poll (liniile raman in order_line_history).
CREATE TABLE IF NOT EXISTS emag_orders (
  order_id BIGINT PRIMARY KEY,
  channel TEXT NOT NULL DEFAULT 'emag',
  status INTEGER,
  order_date TIMESTAMPTZ,
  modified_at TIMESTAMPTZ,
  payment_mode_id INTEGER,
  payment_mode TEXT,
  customer_name TEXT,
  currency TEXT,
  products_total NUMERIC(12, 4),
  products_total_vat NUMERIC(12, 4),
  shipping_tax NUMERIC(12, 4),
  vouchers_total NUMERIC(12, 4),
  raw JSONB,
  received_via TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_emag_orders_date
  ON emag_orders (order_date DESC);

-- Starea operatorului pentru apelurile de review.
CREATE TABLE IF NOT EXISTS review_call_state (
  order_id BIGINT PRIMARY KEY REFERENCES emag_orders(order_id) ON DELETE CASCADE,
  called BOOLEAN NOT NULL DEFAULT FALSE,
  called_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_review_call_state_called
  ON review_call_state (called, updated_at DESC);

-- Review-uri publice eMAG, pe PNK, ca să nu cerem site-ul la fiecare deschidere.
CREATE TABLE IF NOT EXISTS emag_review_cache (
  part_number_key TEXT PRIMARY KEY,
  reviews JSONB NOT NULL DEFAULT '[]',
  http_status INTEGER,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Subscription-uri Web Push (bara de notificări pe telefon / desktop).
CREATE TABLE IF NOT EXISTS push_subscriptions (
  endpoint TEXT PRIMARY KEY,
  p256dh TEXT NOT NULL,
  auth TEXT NOT NULL,
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE order_line_history ADD COLUMN IF NOT EXISTS vat NUMERIC(6, 4);
ALTER TABLE order_line_history
  ADD COLUMN IF NOT EXISTS channel TEXT NOT NULL DEFAULT 'emag';
ALTER TABLE order_line_history
  ADD COLUMN IF NOT EXISTS catalog_product_id INTEGER REFERENCES catalog_products (id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_order_line_order
  ON order_line_history (order_id);

-- Calculatorul din "CALCULATOR INFINITE VENTURES.xlsx": parametri globali + campuri pe produs.
-- pret_cumparare_usd = pretul de fabrica in moneda_fabrica (USD/RMB); pret_cumparare = cost final calculat.
ALTER TABLE settings ADD COLUMN IF NOT EXISTS calculator_params JSONB;
ALTER TABLE catalog_products ADD COLUMN IF NOT EXISTS moneda_fabrica TEXT NOT NULL DEFAULT 'USD';
ALTER TABLE catalog_products ADD COLUMN IF NOT EXISTS nr_bucati INTEGER DEFAULT 5;
ALTER TABLE catalog_products ADD COLUMN IF NOT EXISTS link_ali TEXT;
ALTER TABLE catalog_products ADD COLUMN IF NOT EXISTS link_amz TEXT;
ALTER TABLE catalog_products ADD COLUMN IF NOT EXISTS ce TEXT;
ALTER TABLE catalog_products ADD COLUMN IF NOT EXISTS decizie TEXT;

INSERT INTO settings (id, pret_transport, procentaj_emag, numar_produse, mult_prp, mult_min, mult_max, alte_costuri)
VALUES (1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

INSERT INTO app_meta (key, value)
VALUES ('schema_version', '0')
ON CONFLICT (key) DO NOTHING;
