-- Miscari automate de stoc (comenzi eMAG, anulari, editari manuale pe eMAG, conflicte).
CREATE TABLE IF NOT EXISTS stock_movements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER REFERENCES catalog_products (id) ON DELETE SET NULL,
  channel TEXT NOT NULL DEFAULT 'emag',
  order_id TEXT NOT NULL DEFAULT '',
  line_id TEXT NOT NULL DEFAULT '',
  offer_id TEXT,
  kind TEXT NOT NULL,
  delta NUMERIC(12, 3) NOT NULL DEFAULT 0,
  stock_before NUMERIC(12, 3),
  stock_after NUMERIC(12, 3),
  emag_stock NUMERIC(12, 3),
  trendyol_status TEXT,
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Idempotenta pentru comenzi: aceeasi linie nu se scade/restituie de doua ori.
CREATE UNIQUE INDEX IF NOT EXISTS uq_stock_movements_order_line
  ON stock_movements (channel, order_id, line_id, kind)
  WHERE kind IN ('order', 'order-cancel');

CREATE INDEX IF NOT EXISTS idx_stock_movements_created
  ON stock_movements (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_stock_movements_product
  ON stock_movements (product_id, created_at DESC);

-- Stocul asteptat pe eMAG per oferta (ajustat la comenzi si la push-uri proprii).
CREATE TABLE IF NOT EXISTS emag_stock_snapshot (
  offer_id TEXT PRIMARY KEY,
  general_stock NUMERIC(12, 3),
  seen_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
